version: '3'

tasks:
  vendor:
    cmds:
      - go mod vendor

  test:
    desc: Test client code
    deps:
      - vendor
    cmds:
      - >
        docker run -d
        --name ledger
        --rm
        -e NUMARY_SERVER_HTTP_BIND_ADDRESS=0.0.0.0:3068
        -p 3068:3068
        ghcr.io/numary/ledger:latest
      - defer: docker stop ledger
      - go mod vendor
      - go test